### ISSUE TITLE
Errors on importing version 1.1.5

### ISSUE THREAD

**Issue by brgerig** [GrauGeist/bgg-dark#1]
I get the following errors when importing version 1.1.5: https://pastebin.com/YvPHvSyK

It does seem to work overall, though.

Chrome (up to date) on Windows 10. Fresh install of Stylus, no other userstyles. I do have other modification-type extensions like Tampermonkey.

**Comment by GrauGeist** [comment]
Hm.  I'm not seeing issues under Windows Firefox, but I did see them under Android Firefox.  I'll crosscheck under Chrome.  Thanks!

**Comment by GrauGeist** [comment]
Tentatively resolved as of 1.1.7 earlier today

**Comment by brgerig** [comment]
Strange, I'm still getting identical errors with 1.1.7. I wonder if it's a weird interaction with another extension. I'll have to try disabling my other extensions when I have some time.

**Comment by GrauGeist** [comment]
Hm. I was clean on desktop, but n6nsee it on mobile. Sorry

**Comment by GrauGeist** [comment]
As of 1.1.8, I have clean Importing under Firefox, Chrome, and Android Firefox.  I'm assuming it's "solved".
